import '@/styles/app.css'
import type { Metadata } from 'next'
import { AppProviders } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" data-theme="switchui-light">
      <body>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  )
}
