import '@/styles/app.css'
import { ThemeInitializer } from '@/theme/theme-initializer'
import { ThemeScript } from '@/theme/theme-script'
import { swClsx } from '@repo/ui/utils/clsx'
import type { Metadata, Viewport } from 'next'
import localFont from 'next/font/local'

const pretendard = localFont({
  src: '../../../../assets/fonts/PretendardVariable.woff2',
  display: 'auto',
  weight: '45 920',
  variable: '--font-pretendard',
  preload: true,
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <head>
        <ThemeScript />
      </head>
      <body
        className={swClsx([
          pretendard.className,
          'text-base-content',
          'bg-background',
        ])}
      >
        <ThemeInitializer />
        {children}
      </body>
    </html>
  )
}
